"""add_feedback_json_to_submissions

Revision ID: 5aba277e1361
Revises: f850574aa017
Create Date: 2026-01-29 21:39:10.434502

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5aba277e1361"
down_revision = "f850574aa017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("feedback_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_column("feedback_json")

    # ### end Alembic commands ###
