"""initial schema

Revision ID: 86361256be54
Revises:
Create Date: 2026-01-16 18:10:45.134234

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86361256be54"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_webhooks",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("processed_webhooks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_processed_webhooks_processed_at"),
            ["processed_at"],
            unique=False,
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("github_username", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_username", name="uq_users_github_username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_github_username"), ["github_username"], unique=False
        )

    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("certificate_type", sa.String(length=50), nullable=False),
        sa.Column("verification_code", sa.String(length=64), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phases_completed", sa.Integer(), nullable=False),
        sa.Column("total_phases", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "certificate_type", name="uq_user_certificate"),
        sa.UniqueConstraint("verification_code"),
    )
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.create_index("ix_certificates_user", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_certificates_verification", ["verification_code"], unique=False
        )

    op.create_table(
        "question_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("topic_id", sa.String(length=100), nullable=False),
        sa.Column("question_id", sa.String(length=100), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column("llm_feedback", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_question_attempts_user_question",
            ["user_id", "question_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_question_attempts_user_topic", ["user_id", "topic_id"], unique=False
        )

    op.create_table(
        "step_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("topic_id", sa.String(length=100), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "topic_id", "step_order", name="uq_user_topic_step"
        ),
    )
    with op.batch_alter_table("step_progress", schema=None) as batch_op:
        batch_op.create_index(
            "ix_step_progress_user_topic", ["user_id", "topic_id"], unique=False
        )

    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("requirement_id", sa.String(length=100), nullable=False),
        sa.Column(
            "submission_type",
            sa.Enum(
                "github_profile",
                "profile_readme",
                "repo_fork",
                "repo_url",
                "deployed_app",
                "ctf_token",
                "api_challenge",
                "journal_api_response",
                "workflow_run",
                "repo_with_files",
                "container_image",
                name="submission_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("phase_id", sa.Integer(), nullable=False),
        sa.Column("submitted_value", sa.Text(), nullable=False),
        sa.Column("extracted_username", sa.String(length=255), nullable=True),
        sa.Column("is_validated", sa.Boolean(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "requirement_id", name="uq_user_requirement"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_submissions_user_phase", ["user_id", "phase_id"], unique=False
        )

    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "question_attempt",
                "step_complete",
                "topic_complete",
                "hands_on_validated",
                "phase_complete",
                "certificate_earned",
                name="activity_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("activity_date", sa.Date(), nullable=False),
        sa.Column("reference_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_activities_user_date", ["user_id", "activity_date"], unique=False
        )
        batch_op.create_index(
            "ix_user_activities_user_type", ["user_id", "activity_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.drop_index("ix_user_activities_user_type")
        batch_op.drop_index("ix_user_activities_user_date")

    op.drop_table("user_activities")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index("ix_submissions_user_phase")

    op.drop_table("submissions")
    with op.batch_alter_table("step_progress", schema=None) as batch_op:
        batch_op.drop_index("ix_step_progress_user_topic")

    op.drop_table("step_progress")
    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_question_attempts_user_topic")
        batch_op.drop_index("ix_question_attempts_user_question")

    op.drop_table("question_attempts")
    with op.batch_alter_table("certificates", schema=None) as batch_op:
        batch_op.drop_index("ix_certificates_verification")
        batch_op.drop_index("ix_certificates_user")

    op.drop_table("certificates")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_github_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("processed_webhooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processed_webhooks_processed_at"))

    op.drop_table("processed_webhooks")
    # ### end Alembic commands ###
