"""add verification_completed to submissions

Revision ID: f850574aa017
Revises: add_user_scenarios
Create Date: 2026-01-29 20:48:08.805664

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f850574aa017"
down_revision = "add_user_scenarios"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_question_attempts_lookup",
            ["user_id", "topic_id", "question_id"],
            unique=False,
        )

    with op.batch_alter_table("step_progress", schema=None) as batch_op:
        batch_op.create_index(
            "ix_step_progress_lookup",
            ["user_id", "topic_id", "step_order"],
            unique=False,
        )

    with op.batch_alter_table("submissions", schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(
            sa.Column("verification_completed", sa.Boolean(), nullable=True)
        )

    # Set existing rows to True (assume past submissions completed verification)
    op.execute("UPDATE submissions SET verification_completed = TRUE")

    # Now make it non-nullable
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.alter_column("verification_completed", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_column("verification_completed")

    with op.batch_alter_table("step_progress", schema=None) as batch_op:
        batch_op.drop_index("ix_step_progress_lookup")

    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_question_attempts_lookup")

    # ### end Alembic commands ###
