/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Detailed
         * @description Detailed health check with component status.
         *
         *     Returns status of:
         *     - database: Can execute queries
         *     - azure_auth: Token acquisition working (null if not using Azure)
         *     - pool: Connection pool metrics
         *
         *     Always returns 200 - check individual component statuses for health.
         */
        get: operations["health_detailed_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness endpoint.
         *
         *     Returns 200 only when:
         *     - Background initialization has completed successfully
         *     - The database is reachable
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user info.
         */
        get: operations["get_current_user_api_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Profile Endpoint
         * @description Get a user's public profile by username (GitHub username).
         */
        get: operations["get_public_profile_endpoint_api_user_profile__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/badges/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get badge catalog
         * @description Get the badge catalog for public display.
         */
        get: operations["get_badge_catalog_endpoint_api_user_badges_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Endpoint
         * @description Get complete dashboard data for the current user.
         */
        get: operations["get_dashboard_endpoint_api_user_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Phases Endpoint
         * @description Get all phases with progress for the current user.
         *
         *     For authenticated users:
         *     - Progress statistics
         *     - Locking status based on completion
         *
         *     For unauthenticated users:
         *     - No progress (all null)
         *     - Only Phase 0 unlocked, rest locked
         *
         *     Returns phases in order (0-6).
         */
        get: operations["get_phases_endpoint_api_user_phases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/phases/{phase_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Phase Detail Endpoint
         * @description Get detailed phase info with topics.
         *
         *     Unauthenticated: no progress, only first topic unlocked.
         */
        get: operations["get_phase_detail_endpoint_api_user_phases__phase_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/phases/{phase_slug}/topics/{topic_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic Detail Endpoint
         * @description Get detailed topic info with steps.
         *
         *     Unauthenticated: no progress, content is read-only.
         */
        get: operations["get_topic_detail_endpoint_api_user_phases__phase_slug__topics__topic_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/github/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Github Validation
         * @description Submit a URL or token for hands-on validation.
         */
        post: operations["submit_github_validation_api_github_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Clerk webhooks
         * @description Receives and processes Clerk webhook events for user synchronization. Validates Svix signature and handles user.created, user.updated, and user.deleted events.
         */
        post: operations["clerk_webhook_api_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Streak
         * @description Get the user's current streak information.
         *
         *     Streak calculation allows up to 2 skipped days per week.
         */
        get: operations["get_user_streak_api_activity_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Certificates
         * @description Get all certificates for the authenticated user.
         */
        get: operations["get_user_certificates_api_certificates_get"];
        put?: never;
        /**
         * Generate Certificate Endpoint
         * @description Generate a completion certificate for eligible users.
         */
        post: operations["generate_certificate_endpoint_api_certificates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/eligibility/{certificate_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Certificate Eligibility
         * @description Check if user is eligible for a specific certificate type.
         */
        get: operations["check_certificate_eligibility_api_certificates_eligibility__certificate_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/verify/{verification_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Certificate Endpoint
         * @description Verify a certificate by its verification code (public endpoint).
         */
        get: operations["verify_certificate_endpoint_api_certificates_verify__verification_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/verify/{verification_code}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verified Certificate Pdf Endpoint
         * @description Get the PDF for a verified certificate (public endpoint).
         */
        get: operations["get_verified_certificate_pdf_endpoint_api_certificates_verify__verification_code__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/verify/{verification_code}/png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verified Certificate Png Endpoint
         * @description Get a PNG image for a verified certificate (public endpoint).
         */
        get: operations["get_verified_certificate_png_endpoint_api_certificates_verify__verification_code__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Certificate Pdf Endpoint
         * @description Get the PDF for a certificate.
         */
        get: operations["get_certificate_pdf_endpoint_api_certificates__certificate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Certificate Png Endpoint
         * @description Get a PNG image for a certificate.
         */
        get: operations["get_certificate_png_endpoint_api_certificates__certificate_id__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Step Endpoint
         * @description Mark a learning step as complete.
         *
         *     Steps must be completed in order - you can only complete step N
         *     if steps 1 through N-1 are already complete.
         */
        post: operations["complete_step_endpoint_api_steps_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic Step Progress Endpoint
         * @description Get the step progress for a topic.
         *
         *     Args:
         *         topic_id: The topic ID (e.g., "phase1-topic5")
         */
        get: operations["get_topic_step_progress_endpoint_api_steps__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps/{topic_id}/{step_order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Uncomplete Step Endpoint
         * @description Mark a learning step as incomplete (uncomplete it).
         *
         *     Also removes any steps after this one (cascading uncomplete).
         */
        delete: operations["uncomplete_step_endpoint_api_steps__topic_id___step_order__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityHeatmapDay
         * @description Activity count for a single day (for heatmap display).
         */
        ActivityHeatmapDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Count */
            count: number;
            /** Activity Types */
            activity_types: components["schemas"]["ActivityType"][];
        };
        /**
         * ActivityHeatmapResponse
         * @description Activity heatmap data for profile display.
         */
        ActivityHeatmapResponse: {
            /** Days */
            days: components["schemas"]["ActivityHeatmapDay"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Total Activities */
            total_activities: number;
        };
        /**
         * ActivityType
         * @description Type of user activity for streak and progress tracking.
         * @enum {string}
         */
        ActivityType: "step_complete" | "topic_complete" | "hands_on_validated" | "phase_complete" | "certificate_earned";
        /**
         * BadgeCatalogItem
         * @description Badge metadata for catalog display.
         */
        BadgeCatalogItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Num */
            num: string;
            /** How To */
            how_to: string;
            /** Phase Id */
            phase_id?: number | null;
            /** Phase Name */
            phase_name?: string | null;
        };
        /**
         * BadgeCatalogResponse
         * @description Badge catalog response.
         */
        BadgeCatalogResponse: {
            /** Phase Badges */
            phase_badges: components["schemas"]["BadgeCatalogItem"][];
            /** Streak Badges */
            streak_badges: components["schemas"]["BadgeCatalogItem"][];
            /** Total Badges */
            total_badges: number;
            /** Phase Themes */
            phase_themes: components["schemas"]["PhaseThemeData"][];
        };
        /**
         * BadgeData
         * @description Badge information (service-layer response model).
         */
        BadgeData: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
        };
        /**
         * CertificateData
         * @description Certificate data (service-layer response model).
         */
        CertificateData: {
            /** Id */
            id: number;
            /** Certificate Type */
            certificate_type: string;
            /** Verification Code */
            verification_code: string;
            /** Recipient Name */
            recipient_name: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Phases Completed */
            phases_completed: number;
            /** Total Phases */
            total_phases: number;
        };
        /**
         * CertificateEligibilityResponse
         * @description Response for checking certificate eligibility.
         */
        CertificateEligibilityResponse: {
            /** Is Eligible */
            is_eligible: boolean;
            /** Certificate Type */
            certificate_type: string;
            /** Phases Completed */
            phases_completed: number;
            /** Total Phases */
            total_phases: number;
            /** Completion Percentage */
            completion_percentage: number;
            /** Already Issued */
            already_issued: boolean;
            /** Existing Certificate Id */
            existing_certificate_id?: number | null;
            /** Message */
            message: string;
        };
        /**
         * CertificateRequest
         * @description Request to generate a certificate.
         */
        CertificateRequest: {
            /**
             * Certificate Type
             * @default full_completion
             */
            certificate_type: string;
            /** Recipient Name */
            recipient_name: string;
        };
        /**
         * CertificateVerifyResponse
         * @description Response for certificate verification.
         */
        CertificateVerifyResponse: {
            /** Is Valid */
            is_valid: boolean;
            certificate?: components["schemas"]["CertificateData"] | null;
            /** Message */
            message: string;
        };
        /**
         * DashboardData
         * @description Complete dashboard data (service-layer response model).
         */
        DashboardData: {
            user: components["schemas"]["UserSummaryData"];
            /** Phases */
            phases: components["schemas"]["PhaseSummaryData"][];
            /** Overall Progress */
            overall_progress: number;
            /** Phases Completed */
            phases_completed: number;
            /** Phases Total */
            phases_total: number;
            /** Current Phase */
            current_phase?: number | null;
            /** Badges */
            badges?: components["schemas"]["BadgeData"][];
        };
        /**
         * DetailedHealthResponse
         * @description Detailed health check response with component status.
         */
        DetailedHealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Database */
            database: boolean;
            /** Azure Auth */
            azure_auth?: boolean | null;
            pool?: components["schemas"]["PoolStatusResponse"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HandsOnRequirement
         * @description A hands-on requirement for phase completion.
         *
         *     Used both as API schema and for defining phase requirements
         *     in services/phase_requirements_service.py.
         *
         *     Currently supports Phase 0 and Phase 1 verification types.
         *
         *     To add a new verification type:
         *     1. Add the SubmissionType enum value in models.py
         *     2. Add optional fields here if needed (e.g., challenge_config)
         *     3. Implement the validator in hands_on_verification.py
         */
        HandsOnRequirement: {
            /** Id */
            id: string;
            /** Phase Id */
            phase_id: number;
            submission_type: components["schemas"]["SubmissionType"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Example Url */
            example_url?: string | null;
            /** Note */
            note?: string | null;
            /** Required Repo */
            required_repo?: string | null;
        };
        /**
         * HandsOnSubmissionRequest
         * @description Request to submit a value for hands-on validation.
         */
        HandsOnSubmissionRequest: {
            /** Requirement Id */
            requirement_id: string;
            /** Submitted Value */
            submitted_value: string;
        };
        /**
         * HandsOnSubmissionResponse
         * @description Response for a hands-on submission.
         *
         *     Also used as service-layer response model.
         */
        HandsOnSubmissionResponse: {
            /** Id */
            id: number;
            /** Requirement Id */
            requirement_id: string;
            submission_type: components["schemas"]["SubmissionType"];
            /** Phase Id */
            phase_id: number;
            /** Submitted Value */
            submitted_value: string;
            /** Extracted Username */
            extracted_username?: string | null;
            /** Is Validated */
            is_validated: boolean;
            /** Validated At */
            validated_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Feedback Json */
            feedback_json?: string | null;
        };
        /**
         * HandsOnValidationResult
         * @description Result of validating a hands-on submission.
         */
        HandsOnValidationResult: {
            /** Is Valid */
            is_valid: boolean;
            /** Message */
            message: string;
            /** Username Match */
            username_match?: boolean | null;
            /** Repo Exists */
            repo_exists?: boolean | null;
            submission?: components["schemas"]["HandsOnSubmissionResponse"] | null;
            /** Task Results */
            task_results?: components["schemas"]["TaskResult"][] | null;
            /** Next Retry At */
            next_retry_at?: string | null;
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /**
         * LearningObjective
         * @description A learning objective for a topic.
         */
        LearningObjective: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Order */
            order: number;
        };
        /**
         * LearningStep
         * @description A learning step within a topic.
         */
        LearningStep: {
            /** Order */
            order: number;
            /** Text */
            text: string;
            /** Action */
            action?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Description */
            description?: string | null;
            /** Code */
            code?: string | null;
            /** Secondary Links */
            secondary_links?: components["schemas"]["SecondaryLink"][];
            /** Options */
            options?: components["schemas"]["ProviderOption"][];
        };
        /**
         * PhaseCapstoneOverview
         * @description High-level capstone overview for a phase (public summary).
         */
        PhaseCapstoneOverview: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Includes */
            includes?: string[];
            /** Topic Slug */
            topic_slug?: string | null;
        };
        /**
         * PhaseDetailData
         * @description Full phase detail with topics (service-layer response model).
         */
        PhaseDetailData: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Short Description */
            short_description: string;
            /** Order */
            order: number;
            /** Objectives */
            objectives: string[];
            capstone?: components["schemas"]["PhaseCapstoneOverview"] | null;
            hands_on_verification?: components["schemas"]["PhaseHandsOnVerificationOverview"] | null;
            /** Topics */
            topics: components["schemas"]["TopicSummaryData"][];
            progress?: components["schemas"]["PhaseProgressData"] | null;
            /** Hands On Requirements */
            hands_on_requirements?: components["schemas"]["HandsOnRequirement"][];
            /** Hands On Submissions */
            hands_on_submissions?: components["schemas"]["HandsOnSubmissionResponse"][];
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            /**
             * All Topics Complete
             * @default false
             */
            all_topics_complete: boolean;
            /**
             * All Hands On Validated
             * @default false
             */
            all_hands_on_validated: boolean;
            /**
             * Is Phase Complete
             * @default false
             */
            is_phase_complete: boolean;
        };
        /**
         * PhaseHandsOnVerificationOverview
         * @description High-level hands-on verification overview for a phase (public summary).
         */
        PhaseHandsOnVerificationOverview: {
            /** Summary */
            summary: string;
            /** Includes */
            includes?: string[];
            /** Requirements */
            requirements?: components["schemas"]["HandsOnRequirement"][];
        };
        /**
         * PhaseProgressData
         * @description Progress status for a phase (service-layer response model).
         */
        PhaseProgressData: {
            /** Steps Completed */
            steps_completed: number;
            /** Steps Required */
            steps_required: number;
            /** Hands On Validated */
            hands_on_validated: number;
            /** Hands On Required */
            hands_on_required: number;
            /** Percentage */
            percentage: number;
            /** Status */
            status: string;
        };
        /**
         * PhaseSummaryData
         * @description Phase summary data (service-layer response model).
         */
        PhaseSummaryData: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Short Description */
            short_description: string;
            /** Order */
            order: number;
            /** Topics Count */
            topics_count: number;
            /** Objectives */
            objectives?: string[];
            capstone?: components["schemas"]["PhaseCapstoneOverview"] | null;
            hands_on_verification?: components["schemas"]["PhaseHandsOnVerificationOverview"] | null;
            progress?: components["schemas"]["PhaseProgressData"] | null;
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
        };
        /**
         * PhaseThemeData
         * @description Phase theme metadata for UI display.
         */
        PhaseThemeData: {
            /** Phase Id */
            phase_id: number;
            /** Icon */
            icon: string;
            /** Bg Class */
            bg_class: string;
            /** Border Class */
            border_class: string;
            /** Text Class */
            text_class: string;
        };
        /**
         * PoolStatusResponse
         * @description Connection pool status.
         */
        PoolStatusResponse: {
            /** Pool Size */
            pool_size: number;
            /** Checked Out */
            checked_out: number;
            /** Overflow */
            overflow: number;
            /** Checked In */
            checked_in: number;
        };
        /**
         * ProviderOption
         * @description Cloud provider-specific option for a learning step.
         */
        ProviderOption: {
            /** Provider */
            provider: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PublicProfileResponse
         * @description Public user profile information.
         *
         *     Progress is tracked at the phase level:
         *     - A phase is complete when all steps + hands-on requirements are done
         *     - phases_completed counts fully completed phases
         *     - current_phase is the first incomplete phase (or highest if all done)
         */
        PublicProfileResponse: {
            /** Username */
            username?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Current Phase */
            current_phase: number;
            /** Phases Completed */
            phases_completed: number;
            streak: components["schemas"]["StreakData"];
            activity_heatmap: components["schemas"]["ActivityHeatmapResponse"];
            /**
             * Member Since
             * Format: date-time
             */
            member_since: string;
            /** Submissions */
            submissions?: components["schemas"]["PublicSubmission"][];
            /** Badges */
            badges?: components["schemas"]["BadgeData"][];
        };
        /**
         * PublicSubmission
         * @description A validated submission for public display.
         */
        PublicSubmission: {
            /** Requirement Id */
            requirement_id: string;
            submission_type: components["schemas"]["SubmissionType"];
            /** Phase Id */
            phase_id: number;
            /** Submitted Value */
            submitted_value: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Validated At */
            validated_at?: string | null;
        };
        /**
         * SecondaryLink
         * @description A secondary link in a learning step description.
         */
        SecondaryLink: {
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /**
         * StepCompleteRequest
         * @description Request to mark a learning step as complete.
         */
        StepCompleteRequest: {
            /** Topic Id */
            topic_id: string;
            /** Step Order */
            step_order: number;
        };
        /**
         * StepProgressData
         * @description Step progress data for a topic (service-layer response model).
         */
        StepProgressData: {
            /** Topic Id */
            topic_id: string;
            /** Completed Steps */
            completed_steps: number[];
            /** Total Steps */
            total_steps: number;
            /** Next Unlocked Step */
            next_unlocked_step: number;
        };
        /**
         * StepProgressResponse
         * @description Response for a single step's progress.
         */
        StepProgressResponse: {
            /** Topic Id */
            topic_id: string;
            /** Step Order */
            step_order: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /**
         * StepUncompleteResponse
         * @description Response for uncompleting a step.
         */
        StepUncompleteResponse: {
            /** Status */
            status: string;
            /** Deleted Count */
            deleted_count: number;
        };
        /**
         * StreakData
         * @description User's streak information (service-layer response model).
         */
        StreakData: {
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Total Activity Days */
            total_activity_days: number;
            /** Last Activity Date */
            last_activity_date?: string | null;
            /** Streak Alive */
            streak_alive: boolean;
        };
        /**
         * SubmissionType
         * @description Type of submission for hands-on verification.
         *
         *     Currently supports Phase 0, Phase 1, and Phase 2 verification types.
         *
         *     To add a new verification type:
         *     1. Add the enum value here
         *     2. Add a validator function in the appropriate module:
         *        - GitHub-based: api/services/github_hands_on_verification_service.py
         *        - JSON validation: api/services/journal_verification_service.py
         *        - Or create a new module for complex verification types
         *     3. Add the routing case in validate_submission() in hands_on_verification.py
         *     4. Add optional fields to HandsOnRequirement schema if needed
         * @enum {string}
         */
        SubmissionType: "github_profile" | "profile_readme" | "repo_fork" | "ctf_token" | "networking_token" | "journal_api_response" | "code_analysis" | "deployed_api" | "container_image" | "cicd_pipeline" | "terraform_iac" | "kubernetes_manifests" | "security_scanning";
        /**
         * TaskResult
         * @description Result of verifying a single task in code analysis.
         *
         *     Used by CODE_ANALYSIS validation to provide detailed per-task feedback.
         */
        TaskResult: {
            /** Task Name */
            task_name: string;
            /** Passed */
            passed: boolean;
            /** Feedback */
            feedback: string;
        };
        /**
         * TopicDetailData
         * @description Full topic detail with steps (service-layer response model).
         */
        TopicDetailData: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Order */
            order: number;
            /** Is Capstone */
            is_capstone: boolean;
            /** Learning Steps */
            learning_steps: components["schemas"]["LearningStep"][];
            /** Learning Objectives */
            learning_objectives?: components["schemas"]["LearningObjective"][];
            progress?: components["schemas"]["TopicProgressData"] | null;
            /** Completed Step Orders */
            completed_step_orders?: number[];
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            /**
             * Is Topic Locked
             * @default false
             */
            is_topic_locked: boolean;
            /** Previous Topic Name */
            previous_topic_name?: string | null;
        };
        /**
         * TopicProgressData
         * @description Progress status for a topic (service-layer response model).
         */
        TopicProgressData: {
            /** Steps Completed */
            steps_completed: number;
            /** Steps Total */
            steps_total: number;
            /** Percentage */
            percentage: number;
            /** Status */
            status: string;
        };
        /**
         * TopicSummaryData
         * @description Topic summary data (service-layer response model).
         */
        TopicSummaryData: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Order */
            order: number;
            /** Is Capstone */
            is_capstone: boolean;
            /** Steps Count */
            steps_count: number;
            progress?: components["schemas"]["TopicProgressData"] | null;
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
        };
        /**
         * UserCertificatesResponse
         * @description All certificates for a user.
         */
        UserCertificatesResponse: {
            /** Certificates */
            certificates: components["schemas"]["CertificateData"][];
            /** Full Completion Eligible */
            full_completion_eligible: boolean;
        };
        /**
         * UserResponse
         * @description User response schema (also used as service-layer response model).
         */
        UserResponse: {
            /** Email */
            email: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Github Username */
            github_username?: string | null;
            /** Id */
            id: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserSummaryData
         * @description User summary data (service-layer response model).
         */
        UserSummaryData: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Github Username */
            github_username?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookResponse
         * @description Response for webhook processing.
         */
        WebhookResponse: {
            /** Status */
            status: string;
            /** Event Type */
            event_type?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_detailed_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service unavailable - init failed or DB unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Database unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_api_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_public_profile_endpoint_api_user_profile__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_badge_catalog_endpoint_api_user_badges_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Badge catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadgeCatalogResponse"];
                };
            };
        };
    };
    get_dashboard_endpoint_api_user_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_phases_endpoint_api_user_phases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseSummaryData"][];
                };
            };
        };
    };
    get_phase_detail_endpoint_api_user_phases__phase_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phase_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseDetailData"];
                };
            };
            /** @description Phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_detail_endpoint_api_user_phases__phase_slug__topics__topic_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phase_slug: string;
                topic_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailData"];
                };
            };
            /** @description Topic or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_github_validation_api_github_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandsOnSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnValidationResult"];
                };
            };
            /** @description GitHub username required to submit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requirement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited or cooldown active */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clerk_webhook_api_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Missing webhook headers or invalid signature */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook signing secret not configured */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_streak_api_activity_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakData"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_certificates_api_certificates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCertificatesResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_certificate_endpoint_api_certificates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateData"];
                };
            };
            /** @description User not eligible for certificate */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Certificate already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_certificate_eligibility_api_certificates_eligibility__certificate_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateEligibilityResponse"];
                };
            };
            /** @description Invalid certificate type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificate_endpoint_api_certificates_verify__verification_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateVerifyResponse"];
                };
            };
            /** @description Validation error - code too short or long */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_verified_certificate_pdf_endpoint_api_certificates_verify__verification_code__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verified_certificate_png_endpoint_api_certificates_verify__verification_code__png_get: {
        parameters: {
            query?: {
                scale?: number;
            };
            header?: never;
            path: {
                verification_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG certificate image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description PNG generation not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_certificate_pdf_endpoint_api_certificates__certificate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_certificate_png_endpoint_api_certificates__certificate_id__png_get: {
        parameters: {
            query?: {
                scale?: number;
            };
            header?: never;
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG certificate image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description PNG generation not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    complete_step_endpoint_api_steps_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepProgressResponse"];
                };
            };
            /** @description Step already completed, not unlocked, or invalid step order */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Topic not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_step_progress_endpoint_api_steps__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepProgressData"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Topic not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uncomplete_step_endpoint_api_steps__topic_id___step_order__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
                step_order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepUncompleteResponse"];
                };
            };
            /** @description Invalid step order */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Topic not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
