"""Infrastructure as Code lab token verification.

This module verifies completion tokens generated by the DevOps lab for all
supported providers.
"""

import base64
import hashlib
import hmac
import json
import logging
from datetime import UTC, datetime

from core.config import get_settings
from schemas import IaCVerificationResult

logger = logging.getLogger(__name__)

REQUIRED_CHALLENGES_BY_TYPE = {
    "devops-lab-azure": 7,
    "devops-lab-aws": 7,
    "devops-lab-gcp": 7,
}

ACCEPTED_CHALLENGE_TYPES = {
    "devops-lab-azure",
    "devops-lab-aws",
    "devops-lab-gcp",
}


def _get_master_secret() -> str:
    """Get the master secret for token verification.

    Uses LABS_VERIFICATION_SECRET shared across hands-on lab verifiers.
    """
    settings = get_settings()
    secret = settings.labs_verification_secret
    if not settings.debug and not secret:
        raise RuntimeError("Labs verification secret is not configured")
    if not secret:
        logger.warning(
            "iac.secret.missing",
            extra={"hint": "Set LABS_VERIFICATION_SECRET in .env"},
        )
    return secret


def _derive_secret(instance_id: str) -> str:
    """Derive instance-specific verification secret."""
    master_secret = _get_master_secret()
    data = f"{master_secret}:{instance_id}"
    return hashlib.sha256(data.encode()).hexdigest()


def verify_iac_token(token: str, oauth_github_username: str) -> IaCVerificationResult:
    """Verify an IaC lab completion token."""
    try:
        try:
            decoded = base64.b64decode(token).decode("utf-8")
            token_data = json.loads(decoded)
        except (ValueError, json.JSONDecodeError):
            return IaCVerificationResult(
                is_valid=False,
                message="Invalid token format. Could not decode the token.",
            )

        payload = token_data.get("payload")
        signature = token_data.get("signature")

        if not payload or not signature:
            return IaCVerificationResult(
                is_valid=False,
                message="Invalid token structure. Missing payload or signature.",
            )

        challenge_type = payload.get("challenge") or ""
        if challenge_type not in ACCEPTED_CHALLENGE_TYPES:
            return IaCVerificationResult(
                is_valid=False,
                message=(
                    f"Invalid challenge type '{challenge_type}'. "
                    "Make sure you're submitting a token from the DevOps lab."
                ),
                challenge_type=challenge_type or None,
            )

        token_username = (payload.get("github_username") or "").lower()
        oauth_username_lower = oauth_github_username.lower()
        if token_username != oauth_username_lower:
            return IaCVerificationResult(
                is_valid=False,
                message=(
                    "GitHub username mismatch. "
                    f"Token is for '{payload.get('github_username')}', "
                    f"but you signed in as '{oauth_github_username}'."
                ),
                challenge_type=challenge_type,
            )

        instance_id = payload.get("instance_id")
        if not instance_id:
            return IaCVerificationResult(
                is_valid=False,
                message="Invalid token: missing instance ID.",
                challenge_type=challenge_type,
            )

        try:
            verification_secret = _derive_secret(instance_id)
        except RuntimeError:
            logger.exception(
                "iac.verification.misconfigured",
                extra={"expected_username": oauth_github_username},
            )
            return IaCVerificationResult(
                is_valid=False,
                message="IaC lab verification is not available right now.",
                server_error=True,
                challenge_type=challenge_type,
            )

        payload_str = json.dumps(payload, separators=(",", ":"))
        expected_sig = hmac.new(
            verification_secret.encode(),
            payload_str.encode(),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected_sig):
            return IaCVerificationResult(
                is_valid=False,
                message="Invalid token signature. Token may have been tampered with.",
                challenge_type=challenge_type,
            )

        challenges = payload.get("challenges", 0)
        required_challenges = REQUIRED_CHALLENGES_BY_TYPE[challenge_type]
        if challenges != required_challenges:
            return IaCVerificationResult(
                is_valid=False,
                message=(
                    f"Incomplete incidents: {challenges}/{required_challenges}. "
                    "Resolve all incidents to get a valid token."
                ),
                challenge_type=challenge_type,
            )

        timestamp = payload.get("timestamp", 0)
        now = datetime.now(UTC).timestamp()
        if timestamp > now + 3600:
            return IaCVerificationResult(
                is_valid=False,
                message="Invalid timestamp. The token appears to be from the future.",
                challenge_type=challenge_type,
            )

        logger.info(
            "iac.verification.passed",
            extra={
                "github_username": payload.get("github_username"),
                "challenge_type": challenge_type,
                "challenges": challenges,
            },
        )

        provider_name = challenge_type.removeprefix("devops-lab-").upper()

        return IaCVerificationResult(
            is_valid=True,
            message=(
                "🎉 Congratulations! You have completed the IaC lab "
                f"for the {provider_name} provider."
            ),
            github_username=payload.get("github_username"),
            completion_date=payload.get("date"),
            completion_time=payload.get("time"),
            challenges_completed=challenges,
            challenge_type=challenge_type,
        )

    except Exception as e:
        logger.exception(
            "iac.token.verification.failed",
            extra={"error": str(e), "expected_username": oauth_github_username},
        )
        return IaCVerificationResult(
            is_valid=False,
            message="Token verification failed. Please try again or contact support.",
            server_error=True,
        )
