"""Networking Lab Token Verification.

This module verifies completion tokens generated by the Networking Lab challenges.
The verification process ensures:
1. Token is properly signed with HMAC
2. GitHub username in the token matches the authenticated user
3. All 4 incidents are resolved
4. Challenge type is "networking-lab-azure"
5. Timestamp is valid

Token format matches the Linux CTF for consistency but validates
networking-specific challenges.
"""

import base64
import hashlib
import hmac
import json
import logging
from datetime import UTC, datetime

from core.config import get_settings
from schemas import NetworkingLabVerificationResult

logger = logging.getLogger(__name__)

REQUIRED_CHALLENGES = 4
EXPECTED_CHALLENGE_TYPE = "networking-lab-azure"


def _get_master_secret() -> str:
    """Get the master secret for token verification.

    Uses the same LABS_VERIFICATION_SECRET as Linux CTF since both labs
    use the same secret derivation pattern.

    Raises:
        RuntimeError: If secret is not configured in production.
    """
    settings = get_settings()
    secret = settings.labs_verification_secret
    if not settings.debug and not secret:
        raise RuntimeError("Labs verification secret is not configured")
    if not secret:
        logger.warning(
            "networking.secret.missing",
            extra={"hint": "Set LABS_VERIFICATION_SECRET in .env"},
        )
    return secret


def _derive_secret(instance_id: str) -> str:
    """Derive instance-specific secret from master secret.

    Uses SHA-256 hash of "{master_secret}:{instance_id}" to create
    a unique verification secret per deployment instance.
    """
    master_secret = _get_master_secret()
    data = f"{master_secret}:{instance_id}"
    return hashlib.sha256(data.encode()).hexdigest()


def verify_networking_token(
    token: str, oauth_github_username: str
) -> NetworkingLabVerificationResult:
    """Verify a Networking Lab completion token.

    Args:
        token: Base64-encoded completion token from the networking lab
        oauth_github_username: GitHub username from OAuth (must match token)

    Returns:
        NetworkingLabVerificationResult with verification status and details
    """
    try:
        # Decode and parse token
        try:
            decoded = base64.b64decode(token).decode("utf-8")
            token_data = json.loads(decoded)
        except (ValueError, json.JSONDecodeError):
            return NetworkingLabVerificationResult(
                is_valid=False,
                message="Invalid token format. Could not decode the token.",
            )

        payload = token_data.get("payload")
        signature = token_data.get("signature")

        if not payload or not signature:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message="Invalid token structure. Missing payload or signature.",
            )

        # Verify challenge type
        challenge_type = payload.get("challenge")
        if challenge_type != EXPECTED_CHALLENGE_TYPE:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message=(
                    f"Invalid challenge type. Expected '{EXPECTED_CHALLENGE_TYPE}', "
                    f"got '{challenge_type}'. Make sure you're submitting "
                    "a token from the Networking Lab."
                ),
            )

        # Verify username match
        token_username = (payload.get("github_username") or "").lower()
        oauth_username_lower = oauth_github_username.lower()

        if token_username != oauth_username_lower:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message=(
                    f"GitHub username mismatch. "
                    f"Token is for '{payload.get('github_username')}', "
                    f"but you signed in as '{oauth_github_username}'."
                ),
            )

        # Verify instance ID exists
        instance_id = payload.get("instance_id")
        if not instance_id:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message="Invalid token: missing instance ID.",
            )

        # Derive verification secret
        try:
            verification_secret = _derive_secret(instance_id)
        except RuntimeError:
            logger.exception("Networking lab verification misconfigured")
            return NetworkingLabVerificationResult(
                is_valid=False,
                message="Networking lab verification is not available right now.",
            )

        # Verify HMAC signature
        payload_str = json.dumps(payload, separators=(",", ":"))

        expected_sig = hmac.new(
            verification_secret.encode(),
            payload_str.encode(),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected_sig):
            return NetworkingLabVerificationResult(
                is_valid=False,
                message=(
                    "Invalid token signature. The token may have been tampered with."
                ),
            )

        # Verify challenge count
        challenges = payload.get("challenges", 0)
        if challenges != REQUIRED_CHALLENGES:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message=(
                    f"Incomplete incidents: {challenges}/{REQUIRED_CHALLENGES}. "
                    "Resolve all incidents to get a valid token."
                ),
            )

        # Verify timestamp is not from the future
        timestamp = payload.get("timestamp", 0)
        now = datetime.now(UTC).timestamp()
        if timestamp > now + 3600:
            return NetworkingLabVerificationResult(
                is_valid=False,
                message="Invalid timestamp. The token appears to be from the future.",
            )

        # Success
        return NetworkingLabVerificationResult(
            is_valid=True,
            message=(
                f"🎉 Congratulations! You have resolved all {REQUIRED_CHALLENGES} "
                "network incidents in the Networking Lab!"
            ),
            github_username=payload.get("github_username"),
            completion_date=payload.get("date"),
            completion_time=payload.get("time"),
            challenges_completed=challenges,
            challenge_type=challenge_type,
        )

    except Exception as e:
        logger.exception(
            "networking.token.verification.failed",
            extra={"error": str(e)},
        )
        return NetworkingLabVerificationResult(
            is_valid=False,
            message="Token verification failed. Please try again or contact support.",
        )
