"""Networking Lab Token Verification.

This module verifies completion tokens generated by the Networking Lab challenges.
The verification process ensures:
1. Token is properly signed with HMAC
2. GitHub username in the token matches the authenticated user
3. All 4 incidents are resolved
4. Challenge type is one of: networking-lab-azure,
   networking-lab-aws, networking-lab-gcp
5. Timestamp is valid

Shared token verification logic (decoding, HMAC, username matching)
lives in ``services.token_verification_base``.
"""

from schemas import NetworkingLabVerificationResult
from services.token_verification_base import LabConfig, verify_lab_token

_NETWORKING_CONFIG = LabConfig(
    required_challenges=4,
    challenge_label="incidents",
    log_prefix="networking",
    service_display_name="Networking Lab",
    success_message=(
        "🎉 Congratulations! You have resolved all 4 "
        "network incidents in the Networking Lab!"
    ),
    accepted_challenge_types=frozenset(
        {
            "networking-lab-azure",
            "networking-lab-aws",
            "networking-lab-gcp",
        }
    ),
)

# Public constants derived from config (used by tests)
REQUIRED_CHALLENGES = _NETWORKING_CONFIG.required_challenges
assert _NETWORKING_CONFIG.accepted_challenge_types is not None
ACCEPTED_CHALLENGE_TYPES: frozenset[str] = _NETWORKING_CONFIG.accepted_challenge_types


def verify_networking_token(
    token: str, oauth_github_username: str
) -> NetworkingLabVerificationResult:
    """Verify a Networking Lab completion token.

    Args:
        token: Base64-encoded completion token from the networking lab
        oauth_github_username: GitHub username from OAuth (must match token)

    Returns:
        NetworkingLabVerificationResult with verification status and details
    """
    result = verify_lab_token(token, oauth_github_username, _NETWORKING_CONFIG)
    return NetworkingLabVerificationResult(**result)
