"""Lint Alembic migration files in the active chain.

Enforces two invariants for every revision reachable from a current head:

1. Filename / revision id matches ``NNNN_descriptive_slug``.
2. If the migration's docstring mentions ``Revises: <id>``, that id must
   match the file's ``down_revision = ...`` value. This catches the stale-
   docstring bug class (e.g. revision 0013 used to claim ``Revises: 0012``
   while its code pointed to ``039941763eac``).

New migrations created with ``scripts/new_migration.py`` use a template
that omits the ``Revises:`` line entirely, so the docstring lint applies
only to legacy files that still have it.

Dead off-chain revisions are ignored because
``ScriptDirectory.walk_revisions()`` only walks the active graph.

Run from ``api/`` so ``alembic.ini`` resolves correctly::

    uv run python scripts/check_migration_naming.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

_REVISION_ID_PATTERN = re.compile(r"^\d{4}_[a-z0-9_]+$")
_DOCSTRING_REVISES_PATTERN = re.compile(r"^\s*Revises:\s*(\S+)\s*$", re.MULTILINE)
# A "real" revision id used as the value of Revises: must look like one of:
# - empty (base revision, paired with ``down_revision = None``)
# - NNNN_descriptive_slug
# - a 12-char hex string (Alembic's default ``%(rev)s`` autogenerate format)
_REVISION_VALUE_PATTERN = re.compile(r"^(\d{4}_[a-z0-9_]+|[0-9a-f]{12})$")

# Single legacy autogenerated revision that predates the NNNN_descriptive
# convention. Renaming would require either inserting an out-of-pattern id
# (``0012a_...``) or renumbering 11 downstream migrations, both of which
# carry more risk than the cosmetic gain. New migrations must conform.
_LEGACY_REVISION_IDS: frozenset[str] = frozenset({"039941763eac"})


def _check_docstring_consistency(
    path: Path, code_down_revision: str | list[str] | tuple[str, ...] | None
) -> str | None:
    """Return a complaint string if the docstring's Revises: line is stale.

    Multi-parent merge revisions (``down_revision`` is a list or tuple) are
    skipped because a single ``Revises: X`` docstring line can't
    unambiguously represent multiple parents.
    """
    if isinstance(code_down_revision, (list, tuple)):
        return None
    text = path.read_text()
    match = _DOCSTRING_REVISES_PATTERN.search(text)
    if match is None:
        return None
    doc_value = match.group(1)
    # Skip values that don't look like a real revision id — they're false
    # positives from the regex (e.g. capturing text from another line).
    if not _REVISION_VALUE_PATTERN.match(doc_value):
        return None
    expected = code_down_revision or ""
    if doc_value != expected:
        return (
            f"{path.name}: docstring 'Revises: {doc_value}' "
            f"does not match down_revision = {code_down_revision!r}"
        )
    return None


def main() -> int:
    cfg = Config("alembic.ini")
    script = ScriptDirectory.from_config(cfg)

    naming_failures: list[str] = []
    docstring_failures: list[str] = []
    total = 0
    for rev in script.walk_revisions():
        total += 1

        if rev.revision not in _LEGACY_REVISION_IDS and not _REVISION_ID_PATTERN.match(
            rev.revision
        ):
            naming_failures.append(rev.revision)

        path = Path(rev.path) if rev.path else None
        if path is not None:
            complaint = _check_docstring_consistency(path, rev.down_revision)
            if complaint is not None:
                docstring_failures.append(complaint)

    exit_code = 0
    if naming_failures:
        print(
            "Non-conforming revision IDs in active migration chain "
            f"(expected NNNN_descriptive_slug): {naming_failures}",
            file=sys.stderr,
        )
        exit_code = 1
    if docstring_failures:
        print("Stale 'Revises:' docstrings:", file=sys.stderr)
        for line in docstring_failures:
            print(f"  {line}", file=sys.stderr)
        exit_code = 1

    if exit_code == 0:
        print(
            f"OK: {total} revision(s) match naming convention "
            "and docstrings are consistent with code."
        )
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
